### ISSUE TITLE
link to remove association on has_many through does not work

### ISSUE THREAD

**Issue by zyferdigital** [nathanvda/cocoon_simple_form_demo#5]
1. Downloaded and ran the cocoon_simple_form_demo. 
2. Create a project and add a few tags (has_many through) and save.
3. Edit the project, clicking remove on some/all the tags and click "update project" to save
4. Tags which were "removed" are still present on the project. The association should be deleted.

**Comment by Susztar** [comment]
First of all, thank you nathanvda for the gem! I have had the similar issue, and I found the solution (you may have already found this out):
In project model allow destroy for the nested attribute project_tags:
accepts_nested_attributes_for :project_tags, :allow_destroy => true

**Comment by nathanvda** [comment]
The project has been updated, and everything should be fully functional now. Thanks @Susztar for the tip :+1: :smile:
