### ISSUE TITLE
undefined method `reflect_on_association' for NilClass:Class for double nested

### ISSUE THREAD

**Issue by kevinhq** [nathanvda/cocoon_simple_form_demo#7]
@nathanvda  - I have made sure the rest of codes are exactly like as your demo example.

Using:
rails (4.1.8)
simple_form (3.1.0)

```
undefined method `reflect_on_association' for NilClass:Class
```

When you called:
```
<%= link_to_add_association 'Add', f, :study_plan_subjects %>
```

The rest of code are exactly like this example.

**Comment by nathanvda** [comment]
Could you please add the issue on the [cocoon](https://github.com/nathanvda/cocoon/issues) repository? And add your view code. It seems `f` is not correct.

**Comment by kevinhq** [comment]
ok
